### ISSUE TITLE
Add column order for workbooks

### ISSUE THREAD

**Issue by Addy81** [eastgenomics/eggd_dias_cnvreports_workflow#3]
To be added as workbooks inputs:

"add_comment_column": true,
"summary": "dias",
"reorder_columns"="CHROM POS END CNVLEN ID ALT QUAL CSQ_SYMBOL CSQ_Feature CSQ_VARIANT_CLASS CSQ_EXON CSQ_INTRON CSQ_STRAND GT CN NP QA QS QSE QSS" ,
"exclude_columns"="REF FILTER CSQ_Allele CSQ_Consequence "

**Comment by mattgarner** [comment]
Also exclude IMPACT
